### ISSUE TITLE
[feat]: addition of types

### ISSUE THREAD

**Issue by ishar19** [thisisyashgarg/typist#1]
the program seems to fail when the curl return HTML.
all the applications which works for server rendered pages will return html, hence it'd be a good addition to the app.

**Comment by thisisyashgarg** [comment]
Is this what you expect? @ishar19 

<img width="735" alt="Screenshot 2024-08-24 at 2 25 47 PM" src="https://github.com/user-attachments/assets/e3abb1fa-1a41-4a00-a943-7cd09187ddc1">

**Comment by ishar19** [comment]
Yes, perfect

**Comment by thisisyashgarg** [comment]
cool merging, thanks
